services:
  db:
    image: pgrouting/pgrouting:latest
    container_name: database_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgrouting
      POSTGRES_DB: pgrouting
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/scripts
    ports:
      - 5434:5432
    restart: unless-stopped

  pgrouting_api:
    build: 
      context: .
      dockerfile: Dockerfiles/api/Dockerfile
    container_name: pgrouting_api
    ports:
      - "8000:8000"
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: pgrouting
      PGDATABASE: pgrouting
    volumes:
      - ./app:/app
    depends_on:
      - db
  
  importer:
    build:
      context: .
      dockerfile: Dockerfiles/importer/Dockerfile
    depends_on:
      - db
    volumes:
      - ./data:/data
volumes:
  db_data: